import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import AppProvider from "./provider";
import Header from "./components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main style={{ background: "#F1F3F7", width: "100%", height: "100vh" }} >
          <AppProvider>{children}</AppProvider>
        </main>
      </body>
    </html>
  );
}
